import React from 'react';
import { motion } from 'framer-motion';
import FeatureCard from '@/components/molecules/FeatureCard';

const FeaturesSection = () => {
  const features = [
    {
      icon: 'Brain',
      title: 'AI-Powered Roadmaps',
      description: 'Get personalized project roadmaps generated by AI based on your goals, timeline, and industry. No more wondering what to do next.'
    },
    {
      icon: 'CheckSquare',
      title: 'Smart Task Generation',
      description: 'Break down complex goals into actionable daily tasks with AI suggestions, time estimates, and prioritization.'
    },
    {
      icon: 'Zap',
      title: 'Gamified Progress',
      description: 'Earn XP, maintain streaks, unlock achievements, and level up from Builder to Launcher as you complete tasks.'
    },
    {
      icon: 'Target',
      title: 'Daily Motivation Slaps',
      description: 'Get personalized daily nudges, tips, and task suggestions to keep you moving forward even on tough days.'
    },
    {
      icon: 'TrendingUp',
      title: 'Progress Visualization',
      description: 'Track your momentum with beautiful charts, streak counters, and achievement galleries that celebrate your wins.'
    },
    {
      icon: 'Users',
      title: 'Solo Entrepreneur Focus',
      description: 'Designed specifically for digital creators and solo founders who need structure without overwhelming complexity.'
    }
  ];
  
  return (
    <section id="features" className="py-20 lg:py-32">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center space-y-4 mb-16"
        >
          <h2 className="text-3xl lg:text-5xl font-bold">
            Everything you need to{' '}
            <span className="gradient-text">get unstuck</span>
          </h2>
          <p className="text-xl text-slate-400 max-w-3xl mx-auto">
            MentorSlap combines AI guidance with gamification psychology to turn your biggest projects 
            into achievable daily wins.
          </p>
        </motion.div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <FeatureCard
              key={feature.title}
              {...feature}
              delay={index * 0.1}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;